//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlazorTool.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlazorTool.Client.Resources.UIStrings", typeof(UIStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Persons.
        /// </summary>
        public static string ActivityDisplay_AssignedPersons {
            get {
                return ResourceManager.GetString("ActivityDisplay_AssignedPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ActivityDisplay_Category {
            get {
                return ResourceManager.GetString("ActivityDisplay_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Added.
        /// </summary>
        public static string ActivityDisplay_DateAdded {
            get {
                return ResourceManager.GetString("ActivityDisplay_DateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ActivityDisplay_Description {
            get {
                return ResourceManager.GetString("ActivityDisplay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string ActivityDisplay_HoursAbbreviation {
            get {
                return ResourceManager.GetString("ActivityDisplay_HoursAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers.
        /// </summary>
        public static string ActivityDisplay_Workers {
            get {
                return ResourceManager.GetString("ActivityDisplay_Workers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to worker(s).
        /// </summary>
        public static string ActivityDisplay_WorkersCount {
            get {
                return ResourceManager.GetString("ActivityDisplay_WorkersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Load.
        /// </summary>
        public static string ActivityDisplay_WorkLoad {
            get {
                return ResourceManager.GetString("ActivityDisplay_WorkLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities for Work Order:.
        /// </summary>
        public static string ActivityList_ActivitiesForWorkOrder {
            get {
                return ResourceManager.GetString("ActivityList_ActivitiesForWorkOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned.
        /// </summary>
        public static string ActivityList_Assigned {
            get {
                return ResourceManager.GetString("ActivityList_Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string ActivityList_Category {
            get {
                return ResourceManager.GetString("ActivityList_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string ActivityList_Date {
            get {
                return ResourceManager.GetString("ActivityList_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string ActivityList_Description {
            get {
                return ResourceManager.GetString("ActivityList_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string ActivityList_HoursAbbreviation {
            get {
                return ResourceManager.GetString("ActivityList_HoursAbbreviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading activities....
        /// </summary>
        public static string ActivityList_LoadingActivities {
            get {
                return ResourceManager.GetString("ActivityList_LoadingActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No activities found for this work order..
        /// </summary>
        public static string ActivityList_NoActivitiesFound {
            get {
                return ResourceManager.GetString("ActivityList_NoActivitiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total workload:.
        /// </summary>
        public static string ActivityList_TotalWorkload {
            get {
                return ResourceManager.GetString("ActivityList_TotalWorkload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workers.
        /// </summary>
        public static string ActivityList_Workers {
            get {
                return ResourceManager.GetString("ActivityList_Workers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workload.
        /// </summary>
        public static string ActivityList_Workload {
            get {
                return ResourceManager.GetString("ActivityList_Workload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddDate.
        /// </summary>
        public static string Add_Date {
            get {
                return ResourceManager.GetString("Add_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FlexiCMMS.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssetNo:.
        /// </summary>
        public static string AppointmentEditor_AssetNo {
            get {
                return ResourceManager.GetString("AppointmentEditor_AssetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AppointmentEditor_Cancel {
            get {
                return ResourceManager.GetString("AppointmentEditor_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete from scheduler.
        /// </summary>
        public static string AppointmentEditor_DeleteFromScheduler {
            get {
                return ResourceManager.GetString("AppointmentEditor_DeleteFromScheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End:.
        /// </summary>
        public static string AppointmentEditor_End {
            get {
                return ResourceManager.GetString("AppointmentEditor_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to close appointment..
        /// </summary>
        public static string AppointmentEditor_FailedToClose {
            get {
                return ResourceManager.GetString("AppointmentEditor_FailedToClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save appointment..
        /// </summary>
        public static string AppointmentEditor_FailedToSave {
            get {
                return ResourceManager.GetString("AppointmentEditor_FailedToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all required fields..
        /// </summary>
        public static string AppointmentEditor_FillRequiredFields {
            get {
                return ResourceManager.GetString("AppointmentEditor_FillRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish order.
        /// </summary>
        public static string AppointmentEditor_FinishOrder {
            get {
                return ResourceManager.GetString("AppointmentEditor_FinishOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string AppointmentEditor_Save {
            get {
                return ResourceManager.GetString("AppointmentEditor_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        public static string AppointmentEditor_Start {
            get {
                return ResourceManager.GetString("AppointmentEditor_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Person.
        /// </summary>
        public static string Assigned_Person {
            get {
                return ResourceManager.GetString("Assigned_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading changelog:.
        /// </summary>
        public static string ChangelogPage_ErrorLoading {
            get {
                return ResourceManager.GetString("ChangelogPage_ErrorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading changelog....
        /// </summary>
        public static string ChangelogPage_Loading {
            get {
                return ResourceManager.GetString("ChangelogPage_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog Page.
        /// </summary>
        public static string ChangelogPage_Title {
            get {
                return ResourceManager.GetString("ChangelogPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check session:.
        /// </summary>
        public static string CheckSession_FailedToCheckSession {
            get {
                return ResourceManager.GetString("CheckSession_FailedToCheckSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not authenticated, redirecting to login page..
        /// </summary>
        public static string CheckSession_NotAuthenticated {
            get {
                return ResourceManager.GetString("CheckSession_NotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session check failed with status code:.
        /// </summary>
        public static string CheckSession_SessionCheckFailed {
            get {
                return ResourceManager.GetString("CheckSession_SessionCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Date.
        /// </summary>
        public static string Close_Date {
            get {
                return ResourceManager.GetString("Close_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string CustomFilterMenuTemplate_All {
            get {
                return ResourceManager.GetString("CustomFilterMenuTemplate_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DepName.
        /// </summary>
        public static string Department_Name {
            get {
                return ResourceManager.GetString("Department_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeviceCategory.
        /// </summary>
        public static string Device_Category {
            get {
                return ResourceManager.GetString("Device_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string Device_Name {
            get {
                return ResourceManager.GetString("Device_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EndDate.
        /// </summary>
        public static string End_Date {
            get {
                return ResourceManager.GetString("End_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello!.
        /// </summary>
        public static string Greeting {
            get {
                return ResourceManager.GetString("Greeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDERS.
        /// </summary>
        public static string Home_Orders {
            get {
                return ResourceManager.GetString("Home_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCHEDULER.
        /// </summary>
        public static string Home_Scheduler {
            get {
                return ResourceManager.GetString("Home_Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred:.
        /// </summary>
        public static string Login_AnErrorOccurred {
            get {
                return ResourceManager.GetString("Login_AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking....
        /// </summary>
        public static string Login_Checking {
            get {
                return ResourceManager.GetString("Login_Checking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty field.
        /// </summary>
        public static string Login_EmptyField {
            get {
                return ResourceManager.GetString("Login_EmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        public static string Login_Enter {
            get {
                return ResourceManager.GetString("Login_Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Please check your credentials..
        /// </summary>
        public static string Login_LoginFailed {
            get {
                return ResourceManager.GetString("Login_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login to the.
        /// </summary>
        public static string Login_LoginToThe {
            get {
                return ResourceManager.GetString("Login_LoginToThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Login_Password {
            get {
                return ResourceManager.GetString("Login_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select user name....
        /// </summary>
        public static string Login_SelectUserName {
            get {
                return ResourceManager.GetString("Login_SelectUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string Login_UserName {
            get {
                return ResourceManager.GetString("Login_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application is loading ....
        /// </summary>
        public static string MainLayout_ApplicationLoading {
            get {
                return ResourceManager.GetString("MainLayout_ApplicationLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,.
        /// </summary>
        public static string MainLayout_Hello {
            get {
                return ResourceManager.GetString("MainLayout_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string MainLayout_Logout {
            get {
                return ResourceManager.GetString("MainLayout_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string MainLayout_Version {
            get {
                return ResourceManager.GetString("MainLayout_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ModPerson.
        /// </summary>
        public static string Modified_Person {
            get {
                return ResourceManager.GetString("Modified_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string NavMenu_Main {
            get {
                return ResourceManager.GetString("NavMenu_Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation menu.
        /// </summary>
        public static string NavMenu_NavigationMenu {
            get {
                return ResourceManager.GetString("NavMenu_NavigationMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string NavMenu_Orders {
            get {
                return ResourceManager.GetString("NavMenu_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler.
        /// </summary>
        public static string NavMenu_Scheduler {
            get {
                return ResourceManager.GetString("NavMenu_Scheduler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string NavMenu_Settings {
            get {
                return ResourceManager.GetString("NavMenu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string OrdersPage_Clear {
            get {
                return ResourceManager.GetString("OrdersPage_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string OrdersPage_Close {
            get {
                return ResourceManager.GetString("OrdersPage_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact.
        /// </summary>
        public static string OrdersPage_Compact {
            get {
                return ResourceManager.GetString("OrdersPage_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device category.
        /// </summary>
        public static string OrdersPage_DeviceCategory {
            get {
                return ResourceManager.GetString("OrdersPage_DeviceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices:.
        /// </summary>
        public static string OrdersPage_Devices {
            get {
                return ResourceManager.GetString("OrdersPage_Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended.
        /// </summary>
        public static string OrdersPage_Extended {
            get {
                return ResourceManager.GetString("OrdersPage_Extended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string OrdersPage_Filter {
            get {
                return ResourceManager.GetString("OrdersPage_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        public static string OrdersPage_LastYear {
            get {
                return ResourceManager.GetString("OrdersPage_LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading devices list....
        /// </summary>
        public static string OrdersPage_LoadingDevicesList {
            get {
                return ResourceManager.GetString("OrdersPage_LoadingDevicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading order list....
        /// </summary>
        public static string OrdersPage_LoadingOrderList {
            get {
                return ResourceManager.GetString("OrdersPage_LoadingOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string OrdersPage_Month {
            get {
                return ResourceManager.GetString("OrdersPage_Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders.
        /// </summary>
        public static string OrdersPage_Orders {
            get {
                return ResourceManager.GetString("OrdersPage_Orders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quarter.
        /// </summary>
        public static string OrdersPage_Quarter {
            get {
                return ResourceManager.GetString("OrdersPage_Quarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string OrdersPage_SelectAll {
            get {
                return ResourceManager.GetString("OrdersPage_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category....
        /// </summary>
        public static string OrdersPage_SelectCategory {
            get {
                return ResourceManager.GetString("OrdersPage_SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select devices.
        /// </summary>
        public static string OrdersPage_SelectDevices {
            get {
                return ResourceManager.GetString("OrdersPage_SelectDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new....
        /// </summary>
        public static string Scheduler_AddNew {
            get {
                return ResourceManager.GetString("Scheduler_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned persons:.
        /// </summary>
        public static string Scheduler_AssignedPersons {
            get {
                return ResourceManager.GetString("Scheduler_AssignedPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column Width:.
        /// </summary>
        public static string Scheduler_ColumnWidth {
            get {
                return ResourceManager.GetString("Scheduler_ColumnWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Scheduler_Completed {
            get {
                return ResourceManager.GetString("Scheduler_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department:.
        /// </summary>
        public static string Scheduler_Department {
            get {
                return ResourceManager.GetString("Scheduler_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device:.
        /// </summary>
        public static string Scheduler_Device {
            get {
                return ResourceManager.GetString("Scheduler_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device category:.
        /// </summary>
        public static string Scheduler_DeviceCategory {
            get {
                return ResourceManager.GetString("Scheduler_DeviceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string Scheduler_Duplicate {
            get {
                return ResourceManager.GetString("Scheduler_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to close appointment..
        /// </summary>
        public static string Scheduler_FailedToCloseAppointment {
            get {
                return ResourceManager.GetString("Scheduler_FailedToCloseAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In progress.
        /// </summary>
        public static string Scheduler_InProgress {
            get {
                return ResourceManager.GetString("Scheduler_InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading appointments....
        /// </summary>
        public static string Scheduler_LoadingAppointments {
            get {
                return ResourceManager.GetString("Scheduler_LoadingAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading orders….
        /// </summary>
        public static string Scheduler_LoadingOrders {
            get {
                return ResourceManager.GetString("Scheduler_LoadingOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not started.
        /// </summary>
        public static string Scheduler_NotStarted {
            get {
                return ResourceManager.GetString("Scheduler_NotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of days:.
        /// </summary>
        public static string Scheduler_NumberOfDays {
            get {
                return ResourceManager.GetString("Scheduler_NumberOfDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Scheduler_Open {
            get {
                return ResourceManager.GetString("Scheduler_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orders without StartDate:.
        /// </summary>
        public static string Scheduler_OrdersWithoutStartDate {
            get {
                return ResourceManager.GetString("Scheduler_OrdersWithoutStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload all data.
        /// </summary>
        public static string Scheduler_ReloadAllData {
            get {
                return ResourceManager.GetString("Scheduler_ReloadAllData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Scheduler_Remove {
            get {
                return ResourceManager.GetString("Scheduler_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduled orders:.
        /// </summary>
        public static string Scheduler_ScheduledOrders {
            get {
                return ResourceManager.GetString("Scheduler_ScheduledOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select asset....
        /// </summary>
        public static string Scheduler_SelectAsset {
            get {
                return ResourceManager.GetString("Scheduler_SelectAsset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select assigned persons.
        /// </summary>
        public static string Scheduler_SelectAssignedPersons {
            get {
                return ResourceManager.GetString("Scheduler_SelectAssignedPersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select department....
        /// </summary>
        public static string Scheduler_SelectDepartment {
            get {
                return ResourceManager.GetString("Scheduler_SelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select device category....
        /// </summary>
        public static string Scheduler_SelectDeviceCategory {
            get {
                return ResourceManager.GetString("Scheduler_SelectDeviceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show completed orders.
        /// </summary>
        public static string Scheduler_ShowCompletedOrders {
            get {
                return ResourceManager.GetString("Scheduler_ShowCompletedOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot Duration (min):.
        /// </summary>
        public static string Scheduler_SlotDuration {
            get {
                return ResourceManager.GetString("Scheduler_SlotDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to =&gt;.
        /// </summary>
        public static string SchedulerItem_Arrow {
            get {
                return ResourceManager.GetString("SchedulerItem_Arrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string SchedulerItem_Colon {
            get {
                return ResourceManager.GetString("SchedulerItem_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not assigned.
        /// </summary>
        public static string SchedulerSummary_NotAssigned {
            get {
                return ResourceManager.GetString("SchedulerSummary_NotAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string SchedulerSummary_Person {
            get {
                return ResourceManager.GetString("SchedulerSummary_Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string SchedulerSummary_Total {
            get {
                return ResourceManager.GetString("SchedulerSummary_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred:.
        /// </summary>
        public static string Settings_AnErrorOccurred {
            get {
                return ResourceManager.GetString("Settings_AnErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Address.
        /// </summary>
        public static string Settings_ApiAddress {
            get {
                return ResourceManager.GetString("Settings_ApiAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Address cannot be empty..
        /// </summary>
        public static string Settings_ApiAddressEmpty {
            get {
                return ResourceManager.GetString("Settings_ApiAddressEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully connected to API at.
        /// </summary>
        public static string Settings_ApiConnected {
            get {
                return ResourceManager.GetString("Settings_ApiConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error testing API address:.
        /// </summary>
        public static string Settings_ApiTestError {
            get {
                return ResourceManager.GetString("Settings_ApiTestError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will restart!.
        /// </summary>
        public static string Settings_AppRestart {
            get {
                return ResourceManager.GetString("Settings_AppRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Settings_Cancel {
            get {
                return ResourceManager.GetString("Settings_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled..
        /// </summary>
        public static string Settings_Canceled {
            get {
                return ResourceManager.GetString("Settings_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Settings_Confirm {
            get {
                return ResourceManager.GetString("Settings_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the API address?.
        /// </summary>
        public static string Settings_ConfirmApiChange {
            get {
                return ResourceManager.GetString("Settings_ConfirmApiChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Settings_Confirmation {
            get {
                return ResourceManager.GetString("Settings_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Address:.
        /// </summary>
        public static string Settings_NewAddress {
            get {
                return ResourceManager.GetString("Settings_NewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Address:.
        /// </summary>
        public static string Settings_OldAddress {
            get {
                return ResourceManager.GetString("Settings_OldAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will restart to apply the new API address..
        /// </summary>
        public static string Settings_RestartApplyApi {
            get {
                return ResourceManager.GetString("Settings_RestartApplyApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save one or more settings..
        /// </summary>
        public static string Settings_SaveFailed {
            get {
                return ResourceManager.GetString("Settings_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Settings.
        /// </summary>
        public static string Settings_SaveSettings {
            get {
                return ResourceManager.GetString("Settings_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved successfully!.
        /// </summary>
        public static string Settings_SettingsSaved {
            get {
                return ResourceManager.GetString("Settings_SettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test API Address.
        /// </summary>
        public static string Settings_TestApiAddress {
            get {
                return ResourceManager.GetString("Settings_TestApiAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use original colors.
        /// </summary>
        public static string Settings_UseOriginalColors {
            get {
                return ResourceManager.GetString("Settings_UseOriginalColors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong API address.
        /// </summary>
        public static string Settings_WrongApiAddress {
            get {
                return ResourceManager.GetString("Settings_WrongApiAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Start_Date {
            get {
                return ResourceManager.GetString("Start_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted for processing:.
        /// </summary>
        public static string WorkOrder_AcceptedForProcessing {
            get {
                return ResourceManager.GetString("WorkOrder_AcceptedForProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string WorkOrder_Actions {
            get {
                return ResourceManager.GetString("WorkOrder_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added:.
        /// </summary>
        public static string WorkOrder_Added {
            get {
                return ResourceManager.GetString("WorkOrder_Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Person:.
        /// </summary>
        public static string WorkOrder_AssignedPerson {
            get {
                return ResourceManager.GetString("WorkOrder_AssignedPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category:.
        /// </summary>
        public static string WorkOrder_Category {
            get {
                return ResourceManager.GetString("WorkOrder_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Date:.
        /// </summary>
        public static string WorkOrder_ChangeDate {
            get {
                return ResourceManager.GetString("WorkOrder_ChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed:.
        /// </summary>
        public static string WorkOrder_Closed {
            get {
                return ResourceManager.GetString("WorkOrder_Closed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost.
        /// </summary>
        public static string WorkOrder_Cost {
            get {
                return ResourceManager.GetString("WorkOrder_Cost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dates.
        /// </summary>
        public static string WorkOrder_Dates {
            get {
                return ResourceManager.GetString("WorkOrder_Dates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department:.
        /// </summary>
        public static string WorkOrder_Department {
            get {
                return ResourceManager.GetString("WorkOrder_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string WorkOrder_Description {
            get {
                return ResourceManager.GetString("WorkOrder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string WorkOrder_DescriptionTitle {
            get {
                return ResourceManager.GetString("WorkOrder_DescriptionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device.
        /// </summary>
        public static string WorkOrder_Device {
            get {
                return ResourceManager.GetString("WorkOrder_Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End:.
        /// </summary>
        public static string WorkOrder_End {
            get {
                return ResourceManager.GetString("WorkOrder_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executors.
        /// </summary>
        public static string WorkOrder_Executors {
            get {
                return ResourceManager.GetString("WorkOrder_Executors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string WorkOrder_Files {
            get {
                return ResourceManager.GetString("WorkOrder_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string WorkOrder_ID {
            get {
                return ResourceManager.GetString("WorkOrder_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ineffective Count.
        /// </summary>
        public static string WorkOrder_IneffectiveCount {
            get {
                return ResourceManager.GetString("WorkOrder_IneffectiveCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string WorkOrder_Level {
            get {
                return ResourceManager.GetString("WorkOrder_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified By:.
        /// </summary>
        public static string WorkOrder_ModifiedBy {
            get {
                return ResourceManager.GetString("WorkOrder_ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no device.
        /// </summary>
        public static string WorkOrder_NoDevice {
            get {
                return ResourceManager.GetString("WorkOrder_NoDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified.
        /// </summary>
        public static string WorkOrder_NotSpecified {
            get {
                return ResourceManager.GetString("WorkOrder_NotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No workorder found for ID=.
        /// </summary>
        public static string WorkOrder_NoWorkOrderFound {
            get {
                return ResourceManager.GetString("WorkOrder_NoWorkOrderFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order №.
        /// </summary>
        public static string WorkOrder_OrderNo {
            get {
                return ResourceManager.GetString("WorkOrder_OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        public static string WorkOrder_Parts {
            get {
                return ResourceManager.GetString("WorkOrder_Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person Take Date:.
        /// </summary>
        public static string WorkOrder_PersonTakeDate {
            get {
                return ResourceManager.GetString("WorkOrder_PersonTakeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanActCount.
        /// </summary>
        public static string WorkOrder_PlanActCount {
            get {
                return ResourceManager.GetString("WorkOrder_PlanActCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason:.
        /// </summary>
        public static string WorkOrder_Reason {
            get {
                return ResourceManager.GetString("WorkOrder_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Changes.
        /// </summary>
        public static string WorkOrder_RecentChanges {
            get {
                return ResourceManager.GetString("WorkOrder_RecentChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select person....
        /// </summary>
        public static string WorkOrder_SelectPerson {
            get {
                return ResourceManager.GetString("WorkOrder_SelectPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select category....
        /// </summary>
        public static string WorkOrder_SelectWOCategory {
            get {
                return ResourceManager.GetString("WorkOrder_SelectWOCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select level....
        /// </summary>
        public static string WorkOrder_SelectWOLevel {
            get {
                return ResourceManager.GetString("WorkOrder_SelectWOLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select reason....
        /// </summary>
        public static string WorkOrder_SelectWOReason {
            get {
                return ResourceManager.GetString("WorkOrder_SelectWOReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start:.
        /// </summary>
        public static string WorkOrder_Start {
            get {
                return ResourceManager.GetString("WorkOrder_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string WorkOrder_State {
            get {
                return ResourceManager.GetString("WorkOrder_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string WorkOrder_Statistics {
            get {
                return ResourceManager.GetString("WorkOrder_Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Persons:.
        /// </summary>
        public static string WorkOrder_TakePersons {
            get {
                return ResourceManager.GetString("WorkOrder_TakePersons", resourceCulture);
            }
        }
    }
}
